### ISSUE TITLE
Enhance plans view with colors for each context

### ISSUE THREAD

**Issue by cleberjamaral** [jacamo-lang/jacamo-rest#12] opened 2018-12-12 00:26 UTC

**Comment by Sergio-PB** [comment] 2018-12-13 19:22
The tool should also allow updating plans.

**Comment by jomifred** [comment] 2018-12-17 09:47
the part that shows plans is initiated. some improvements can be done yet

**Comment by jomifred** [comment] 2019-02-26 18:16
Duplicate of #15

**Closed by jomifred** 2019-02-26 18:16 UTC
